import { AggregatorProviderConfig } from '../types';

export const ALL_AGGREGATOR_PROVIDERS: AggregatorProviderConfig[] = [
  // Plataformas de Ingressos & Ticketing
  {
    id: 'sympla',
    name: 'Sympla Brasil',
    description: 'API & Crawling de Eventos, Shows, Workshops e Teatros Sympla',
    type: 'api',
    categoryGroup: 'ticketing',
    trustScore: 95,
    enabled: true,
    rateLimitMs: 200,
    totalEventsFound: 4120,
    errorCount: 0,
    url: 'https://www.sympla.com.br/api/v3/events',
  },
  {
    id: 'eventbrite',
    name: 'Eventbrite Global & BR',
    description: 'Feed OpenGraph e API pública Eventbrite para congressos, feiras e artes',
    type: 'api',
    categoryGroup: 'ticketing',
    trustScore: 95,
    enabled: true,
    rateLimitMs: 250,
    totalEventsFound: 2840,
    errorCount: 0,
    url: 'https://www.eventbrite.com.br/api/v3/events/search',
  },
  {
    id: 'meetup',
    name: 'Meetup Communities',
    description: 'Provedor de encontros de tecnologia, astronomia, idiomas e grupos locais',
    type: 'api',
    categoryGroup: 'ticketing',
    trustScore: 90,
    enabled: true,
    rateLimitMs: 300,
    totalEventsFound: 1650,
    errorCount: 0,
    url: 'https://api.meetup.com/find/upcoming_events',
  },
  {
    id: 'fever',
    name: 'Fever Up Brasil',
    description: 'Concertos à luz de velas Candlelight, experiências imersivas e espetáculos',
    type: 'api',
    categoryGroup: 'ticketing',
    trustScore: 92,
    enabled: true,
    rateLimitMs: 350,
    totalEventsFound: 980,
    errorCount: 0,
    url: 'https://feverup.com/api/v1/events',
  },
  {
    id: 'ingresse',
    name: 'Ingresse',
    description: 'Eventos de entretenimento, festivais de música e entretenimento noturno',
    type: 'api',
    categoryGroup: 'ticketing',
    trustScore: 90,
    enabled: true,
    rateLimitMs: 300,
    totalEventsFound: 1420,
    errorCount: 0,
    url: 'https://api.ingresse.com/events',
  },
  {
    id: 'bilheteriadigital',
    name: 'Bilheteria Digital',
    description: 'Shows regionais, feiras gastronômicas e rodeios no interior de SP e BR',
    type: 'api',
    categoryGroup: 'ticketing',
    trustScore: 88,
    enabled: true,
    rateLimitMs: 400,
    totalEventsFound: 870,
    errorCount: 0,
    url: 'https://www.bilheteriadigital.com/api/v2/agenda',
  },
  {
    id: 'shotgun',
    name: 'Shotgun Live',
    description: 'Festivais underground, música eletrônica e artes visuais contemporâneas',
    type: 'api',
    categoryGroup: 'ticketing',
    trustScore: 89,
    enabled: true,
    rateLimitMs: 350,
    totalEventsFound: 640,
    errorCount: 0,
    url: 'https://shotgun.live/api/v1/events',
  },
  {
    id: 'even3',
    name: 'Even3 Acadêmico',
    description: 'Plataforma oficial de simpósios, congressos acadêmicos e jornadas científicas',
    type: 'api',
    categoryGroup: 'ticketing',
    trustScore: 93,
    enabled: true,
    rateLimitMs: 300,
    totalEventsFound: 1210,
    errorCount: 0,
    url: 'https://www.even3.com.br/api/eventos',
  },
  {
    id: 'doity',
    name: 'Doity Eventos',
    description: 'Cursos, palestras corporativas e fóruns regionais de inovação',
    type: 'api',
    categoryGroup: 'ticketing',
    trustScore: 87,
    enabled: true,
    rateLimitMs: 350,
    totalEventsFound: 760,
    errorCount: 0,
    url: 'https://doity.com.br/api/v1/eventos',
  },
  {
    id: 'ticket360',
    name: 'Ticket360',
    description: 'Grandes turnês musicais, arenas e festivais estaduais',
    type: 'api',
    categoryGroup: 'ticketing',
    trustScore: 91,
    enabled: true,
    rateLimitMs: 400,
    totalEventsFound: 1100,
    errorCount: 0,
    url: 'https://www.ticket360.com.br/api/shows',
  },
  {
    id: 'eventim',
    name: 'Eventim Brasil',
    description: 'Turnês internacionais, musicais da Broadway e grandes teatros',
    type: 'api',
    categoryGroup: 'ticketing',
    trustScore: 95,
    enabled: true,
    rateLimitMs: 300,
    totalEventsFound: 1530,
    errorCount: 0,
    url: 'https://www.eventim.com.br/api/v1/events',
  },

  // Instituições & Redes Educacionais
  {
    id: 'sesc',
    name: 'SESC SP & Regional',
    description: 'Programação cultural completa: Teatro, Shows, Cinema, Oficinas e Exibições',
    type: 'rss',
    categoryGroup: 'institutional',
    trustScore: 95,
    enabled: true,
    rateLimitMs: 200,
    totalEventsFound: 3810,
    errorCount: 0,
    url: 'https://www.sescsp.org.br/rss/programacao',
  },
  {
    id: 'sesi',
    name: 'SESI Cultura & Esporte',
    description: 'Teatros SESI, mostras de literatura e projetos musicais comunitários',
    type: 'rss',
    categoryGroup: 'institutional',
    trustScore: 94,
    enabled: true,
    rateLimitMs: 250,
    totalEventsFound: 1890,
    errorCount: 0,
    url: 'https://www.sesisp.org.br/cultura/rss',
  },
  {
    id: 'senac_senai',
    name: 'Senac & Senai Oficinas',
    description: 'Workshops gratuitos de tecnologia, gastronomia, design e moda',
    type: 'rss',
    categoryGroup: 'institutional',
    trustScore: 92,
    enabled: true,
    rateLimitMs: 300,
    totalEventsFound: 1450,
    errorCount: 0,
    url: 'https://www.sp.senac.br/rss/agenda',
  },
  {
    id: 'unicamp',
    name: 'Unicamp (Universidade de Campinas)',
    description: 'Feiras de Ciência, Portas Abertas, Espetáculos da Casa do Lago e Simpósios',
    type: 'schema_html',
    categoryGroup: 'institutional',
    trustScore: 96,
    enabled: true,
    rateLimitMs: 200,
    totalEventsFound: 1930,
    errorCount: 0,
    url: 'https://www.unicamp.br/unicamp/agenda',
  },
  {
    id: 'usp',
    name: 'USP (Universidade de São Paulo)',
    description: 'Cursos abertos, observatório astronômico, concertos da OSUSP e congressos',
    type: 'schema_html',
    categoryGroup: 'institutional',
    trustScore: 96,
    enabled: true,
    rateLimitMs: 200,
    totalEventsFound: 2410,
    errorCount: 0,
    url: 'https://jornal.usp.br/agenda',
  },
  {
    id: 'unesp',
    name: 'UNESP & Institutos Estaduais',
    description: 'Feiras acadêmicas e eventos nos campi do interior (Rio Claro, Bauru, Araraquara)',
    type: 'schema_html',
    categoryGroup: 'institutional',
    trustScore: 94,
    enabled: true,
    rateLimitMs: 300,
    totalEventsFound: 1120,
    errorCount: 0,
    url: 'https://www.unesp.br/agenda',
  },
  {
    id: 'puc_facamp',
    name: 'PUC-Campinas & Facamp',
    description: 'Semanas acadêmicas, fóruns de inovação e mostras de cinema universitário',
    type: 'schema_html',
    categoryGroup: 'institutional',
    trustScore: 91,
    enabled: true,
    rateLimitMs: 300,
    totalEventsFound: 890,
    errorCount: 0,
    url: 'https://www.puc-campinas.edu.br/agenda',
  },
  {
    id: 'ifsp',
    name: 'IFSP & Institutos Federais',
    description: 'Hackathons, feiras tecnológicas e eventos de extensão comunitária',
    type: 'schema_html',
    categoryGroup: 'institutional',
    trustScore: 93,
    enabled: true,
    rateLimitMs: 350,
    totalEventsFound: 740,
    errorCount: 0,
    url: 'https://www.ifsp.edu.br/agenda-eventos',
  },

  // Setor Público & Órgãos de Cultura
  {
    id: 'prefeituras_rmc',
    name: 'Prefeituras da RMC & SP',
    description: 'Diário oficial e portais de Campinas, Hortolândia, Sumaré, Indaiatuba, Americana',
    type: 'schema_html',
    categoryGroup: 'public',
    trustScore: 95,
    enabled: true,
    rateLimitMs: 200,
    totalEventsFound: 5270,
    errorCount: 0,
    url: 'https://www.campinas.sp.gov.br/cultura/agenda',
  },
  {
    id: 'sec_cultura',
    name: 'Secretarias de Cultura',
    description: 'Editais culturais, festas das nações, encontros de folclore e feiras gastronômicas',
    type: 'schema_html',
    categoryGroup: 'public',
    trustScore: 94,
    enabled: true,
    rateLimitMs: 250,
    totalEventsFound: 3120,
    errorCount: 0,
    url: 'https://www.cultura.sp.gov.br/programacao',
  },
  {
    id: 'sec_turismo',
    name: 'Secretarias de Turismo',
    description: 'Rotas de turismo rural, festivais de inverno, corridas de rua e feiras de artesanato',
    type: 'schema_html',
    categoryGroup: 'public',
    trustScore: 92,
    enabled: true,
    rateLimitMs: 300,
    totalEventsFound: 2150,
    errorCount: 0,
    url: 'https://www.turismo.sp.gov.br/agenda-eventos',
  },
  {
    id: 'agenda_estadual',
    name: 'Agenda Cultural Estadual & Municipal',
    description: 'Indexador público unificado de eventos oficiais de todos os municípios paulistas e BR',
    type: 'api',
    categoryGroup: 'public',
    trustScore: 96,
    enabled: true,
    rateLimitMs: 200,
    totalEventsFound: 4890,
    errorCount: 0,
    url: 'https://agendacultural.sp.gov.br/api/v1/events',
  },
  {
    id: 'hortolandia_cultura',
    name: 'Prefeitura de Hortolândia (Cultura & Turismo)',
    description: 'Portal oficial de notícias, eventos e turismo de Hortolândia SP',
    type: 'schema_html',
    categoryGroup: 'public',
    trustScore: 95,
    enabled: true,
    rateLimitMs: 200,
    totalEventsFound: 840,
    errorCount: 0,
    url: 'https://www.hortolandia.sp.gov.br/category/temas-noticias-e-servicos/cultura-e-turismo/',
  },
  {
    id: 'ribeirao_preto',
    name: 'Ribeirão Preto (Cultura, Revide & Shopping)',
    description: 'Prefeitura de Ribeirão Preto, Revide Agenda e RibeirãoShopping Eventos',
    type: 'schema_html',
    categoryGroup: 'public',
    trustScore: 95,
    enabled: true,
    rateLimitMs: 200,
    totalEventsFound: 1420,
    errorCount: 0,
    url: 'https://www.ribeiraopreto.sp.gov.br/portal/cultura',
  },
  {
    id: 'rio_preto',
    name: 'São José do Rio Preto (Cultura & Diário da Região)',
    description: 'Prefeitura de Rio Preto e Diário da Região',
    type: 'schema_html',
    categoryGroup: 'public',
    trustScore: 94,
    enabled: true,
    rateLimitMs: 200,
    totalEventsFound: 1150,
    errorCount: 0,
    url: 'https://www.riopreto.sp.gov.br/',
  },
  {
    id: 'bauru_jcnet',
    name: 'Bauru (Cultura Bauru & JCNET)',
    description: 'Agenda cultural de Bauru e cobertura jornalística JCNET',
    type: 'schema_html',
    categoryGroup: 'public',
    trustScore: 93,
    enabled: true,
    rateLimitMs: 200,
    totalEventsFound: 980,
    errorCount: 0,
    url: 'https://www2.bauru.sp.gov.br/',
  },
  {
    id: 'sorocaba_cruzeiro',
    name: 'Sorocaba (Agenda Sorocaba & Jornal Cruzeiro do Sul)',
    description: 'Agenda oficial de Sorocaba e Jornal Cruzeiro do Sul',
    type: 'schema_html',
    categoryGroup: 'public',
    trustScore: 94,
    enabled: true,
    rateLimitMs: 200,
    totalEventsFound: 1210,
    errorCount: 0,
    url: 'https://www.sorocaba.sp.gov.br/',
  },
  {
    id: 'jundiai_cultura',
    name: 'Jundiaí Cultura',
    description: 'Agenda de cultura, teatros e feiras gastronômicas de Jundiaí',
    type: 'schema_html',
    categoryGroup: 'public',
    trustScore: 95,
    enabled: true,
    rateLimitMs: 200,
    totalEventsFound: 1050,
    errorCount: 0,
    url: 'https://jundiai.sp.gov.br/cultura/',
  },
  {
    id: 'piracicaba_cultural',
    name: 'Piracicaba (Cultura & Jornal de Piracicaba)',
    description: 'Prefeitura de Piracicaba Cultura e Jornal de Piracicaba',
    type: 'schema_html',
    categoryGroup: 'public',
    trustScore: 93,
    enabled: true,
    rateLimitMs: 200,
    totalEventsFound: 890,
    errorCount: 0,
    url: 'https://piracicaba.sp.gov.br/cultura/',
  },
  {
    id: 'saocarlos_araraquara',
    name: 'São Carlos & Araraquara (São Carlos Agora, Pró-Memória e Araraquara.com)',
    description: 'Portais de notícias e cultura de São Carlos e Araraquara',
    type: 'schema_html',
    categoryGroup: 'public',
    trustScore: 93,
    enabled: true,
    rateLimitMs: 200,
    totalEventsFound: 1120,
    errorCount: 0,
    url: 'https://www.saocarlosagora.com.br/',
  },
  {
    id: 'franca_marilia_prudente',
    name: 'Franca, Marília & Presidente Prudente (GCN, Marília Notícias, iFronteira)',
    description: 'Agendas culturais e notícias do norte e oeste paulista',
    type: 'schema_html',
    categoryGroup: 'public',
    trustScore: 92,
    enabled: true,
    rateLimitMs: 200,
    totalEventsFound: 940,
    errorCount: 0,
    url: 'https://gcn.net.br/',
  },
  {
    id: 'regional_nacional',
    name: 'Portais Regionais BR (Sou BH, Zine, Curitiba Cult, Floripa Mil Grau, Poa, Curta Mais, Alô Alô Bahia, Visit Recife, O Povo)',
    description: 'Portais de cultura e turismo de BH, Curitiba, Floripa, Porto Alegre, Goiânia, Salvador, Recife e Fortaleza',
    type: 'schema_html',
    categoryGroup: 'public',
    trustScore: 95,
    enabled: true,
    rateLimitMs: 200,
    totalEventsFound: 4250,
    errorCount: 0,
    url: 'https://www.soubh.com.br/',
  },

  // Espaços Culturais, Museus & Equipamentos
  {
    id: 'museus',
    name: 'Museus & Pinacotecas (MACC, MIS, MASP)',
    description: 'Exposições itinerantes, visitas noturnas com guia e oficinas artísticas',
    type: 'schema_html',
    categoryGroup: 'venues',
    trustScore: 95,
    enabled: true,
    rateLimitMs: 300,
    totalEventsFound: 1340,
    errorCount: 0,
    url: 'https://museus.sp.gov.br/exposicoes',
  },
  {
    id: 'centros_culturais',
    name: 'Centros Culturais & Teatros Municipais',
    description: 'Teatro Castro Mendes, Estação Cultura, Centro de Convivência e teatros parceiros',
    type: 'schema_html',
    categoryGroup: 'venues',
    trustScore: 94,
    enabled: true,
    rateLimitMs: 250,
    totalEventsFound: 2680,
    errorCount: 0,
    url: 'https://teatrocastromendes.com.br/programacao',
  },
  {
    id: 'casas_show',
    name: 'Casas de Show & Espaços Noturnos',
    description: 'Casas de jazz, samba raiz, rock ao vivo e pubs culturais da região',
    type: 'scrape',
    categoryGroup: 'venues',
    trustScore: 88,
    enabled: true,
    rateLimitMs: 350,
    totalEventsFound: 1980,
    errorCount: 0,
    url: 'https://agenda-shows.campinas.br',
  },
  {
    id: 'clubes_eventos',
    name: 'Clubes & Espaços Recreativos',
    description: 'Tênis Clube Campinas, Regatas, Círculo Militar e clubes locais',
    type: 'scrape',
    categoryGroup: 'venues',
    trustScore: 86,
    enabled: true,
    rateLimitMs: 400,
    totalEventsFound: 920,
    errorCount: 0,
    url: 'https://clubes-rmc.org.br/agenda',
  },
  {
    id: 'shoppings',
    name: 'Shoppings & Praças Culturais',
    description: 'Iguatemi Campinas, Parque D. Pedro, Shopping Galleria e shoppings regionais',
    type: 'scrape',
    categoryGroup: 'venues',
    trustScore: 89,
    enabled: true,
    rateLimitMs: 350,
    totalEventsFound: 1470,
    errorCount: 0,
    url: 'https://shoppings-agenda.com.br/eventos',
  },
  {
    id: 'feiras_livres',
    name: 'Feiras Livres, Noturnas & Gastronômicas',
    description: 'Feira Hippie do Convivência, Feira Noturna do Barão e feiras de bairro',
    type: 'scrape',
    categoryGroup: 'venues',
    trustScore: 91,
    enabled: true,
    rateLimitMs: 300,
    totalEventsFound: 1840,
    errorCount: 0,
    url: 'https://feirasdecampinas.sp.gov.br',
  },
  {
    id: 'centros_convencao',
    name: 'Centros de Convenções & Expo',
    description: 'Expo D. Pedro, Royal Palm Hall e pavilhões de negócios e congressos',
    type: 'api',
    categoryGroup: 'venues',
    trustScore: 93,
    enabled: true,
    rateLimitMs: 300,
    totalEventsFound: 1150,
    errorCount: 0,
    url: 'https://expodpedro.com.br/api/agenda',
  },

  // Especificações Abertas, Crawling & IA
  {
    id: 'schema_org',
    name: 'Schema.org Event Markup Reader',
    description: 'Extrator universal de marcações JSON-LD @type: Event em portais da web',
    type: 'schema_html',
    categoryGroup: 'open_spec',
    trustScore: 92,
    enabled: true,
    rateLimitMs: 150,
    totalEventsFound: 6420,
    errorCount: 0,
    url: 'https://schema.org/Event',
  },
  {
    id: 'rss_atom',
    name: 'Feeds Universal RSS / Atom & XML',
    description: 'Leitor automático de feeds RSS/Atom de blogs de cultura e agendas locais',
    type: 'rss',
    categoryGroup: 'open_spec',
    trustScore: 89,
    enabled: true,
    rateLimitMs: 100,
    totalEventsFound: 4310,
    errorCount: 0,
    url: 'https://open-events-rss.org/feed.xml',
  },
  {
    id: 'open_data_api',
    name: 'APIs Públicas & OpenData BR',
    description: 'Portais de dados abertos federais e estaduais de cultura (dados.gov.br)',
    type: 'api',
    categoryGroup: 'open_spec',
    trustScore: 96,
    enabled: true,
    rateLimitMs: 200,
    totalEventsFound: 5120,
    errorCount: 0,
    url: 'https://dados.gov.br/api/v1/cultura/eventos',
  },
  {
    id: 'json_xml_reader',
    name: 'Leitor de Arquivos JSON / OpenGraph',
    description: 'Parser automático de arquivos JSON estáticos e tags meta OpenGraph og:event',
    type: 'api',
    categoryGroup: 'open_spec',
    trustScore: 88,
    enabled: true,
    rateLimitMs: 250,
    totalEventsFound: 2890,
    errorCount: 0,
    url: 'https://opengraph-events.net/feed.json',
  },
];

export const MOCK_RAW_EVENTS_SEED = [
  {
    title: 'Festival da Primavera Sympla Campinas 2026',
    category: 'Música',
    date: '15/09 - 17/09',
    time: '14:00 - 22:00',
    address: 'Parque Taquaral - Portão 5',
    city: 'Campinas - SP',
    price: 'Gratuito',
    isPaid: false,
    organizer: 'Sympla Culturas & Eventos',
    officialLink: 'https://www.sympla.com.br/evento/festival-da-primavera-campinas/192842',
    image: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=800&q=80',
    providerId: 'sympla'
  },
  {
    title: 'Summit Tech & Startups RMC 2026',
    category: 'Tecnologia',
    date: '20/09',
    time: '09:00 - 18:00',
    address: 'Expo D. Pedro - Av. Guilherme Campos, 500',
    city: 'Campinas - SP',
    price: 'R$ 49,90',
    isPaid: true,
    organizer: 'Campinas Tech Alliance & Sympla Biz',
    officialLink: 'https://www.sympla.com.br/evento/summit-tech-rmc/284910',
    image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=800&q=80',
    providerId: 'sympla'
  },
  {
    title: 'Feira Internacional de Cerveja Artesanal e Gastronomia',
    category: 'Gastronomia',
    date: '28/09 - 30/09',
    time: '12:00 - 23:00',
    address: 'Praça da Imprensa - Cambuí',
    city: 'Campinas - SP',
    price: 'R$ 20,00',
    isPaid: true,
    organizer: 'Associação de Cervejeiros & Eventbrite',
    officialLink: 'https://www.eventbrite.com.br/e/feira-cerveja-artesanal-campinas-tickets-991823',
    image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
    providerId: 'eventbrite'
  },
  {
    title: 'Meetup Devs & IA Generativa Campinas',
    category: 'Tecnologia',
    date: '10/09',
    time: '19:00 - 21:30',
    address: 'Hub de Inovação H-59 - Barão Geraldo',
    city: 'Campinas - SP',
    price: 'Gratuito',
    isPaid: false,
    organizer: 'Comunidade Meetup JS & Python Campinas',
    officialLink: 'https://www.meetup.com/pt-BR/campinas-ai-devs/events/301928/',
    image: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=800&q=80',
    providerId: 'meetup'
  },
  {
    title: 'Mostra de Teatro Contemporâneo do SESC',
    category: 'Teatro',
    date: '12/09 - 22/09',
    time: '20:00 - 22:00',
    address: 'SESC Campinas - Rua Dom José I, 270 - Bonfim',
    city: 'Campinas - SP',
    price: 'R$ 15,00',
    isPaid: true,
    organizer: 'SESC São Paulo',
    officialLink: 'https://www.sescsp.org.br/programacao/mostra-teatro-campinas/',
    image: 'https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?auto=format&fit=crop&w=800&q=80',
    providerId: 'sesc'
  },
  {
    title: 'Concertos à Luz de Velas Candlelight: Tributo ao Rock',
    category: 'Música',
    date: '25/09',
    time: '19:30 - 21:00',
    address: 'Teatro Municipal Castro Mendes - Praça Corrêa de Lemos, s/n - Vila Industrial',
    city: 'Campinas - SP',
    price: 'R$ 45,00',
    isPaid: true,
    organizer: 'Fever Up Brasil & Orquestra de Cordas',
    officialLink: 'https://feverup.com/m/candlelight-rock-campinas',
    image: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=800&q=80',
    providerId: 'fever'
  },
  {
    title: 'Feira Gastronômica & Arte Noturna da Estação Cultura',
    category: 'Gastronomia',
    date: '08/09 - 10/09',
    time: '17:00 - 23:00',
    address: 'Estação Cultura - Praça Marechal Floriano Peixoto',
    city: 'Campinas - SP',
    price: 'Gratuito',
    isPaid: false,
    organizer: 'Secretaria Municipal de Cultura e Turismo',
    officialLink: 'https://www.campinas.sp.gov.br/cultura/agenda/estacao-arte.php',
    image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
    providerId: 'prefeituras_rmc'
  },
  {
    title: '34ª Feira de Ciência & Inovação Tecnológica Unicamp',
    category: 'Educação',
    date: '18/09 - 21/09',
    time: '08:30 - 17:00',
    address: 'Ginásio Multidisciplinar da Unicamp - Barão Geraldo',
    city: 'Campinas - SP',
    price: 'Gratuito',
    isPaid: false,
    organizer: 'Pró-Reitoria de Pesquisa Unicamp',
    officialLink: 'https://www.unicamp.br/unicamp/agenda/feira-de-ciencia-inovacao-2026',
    image: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=800&q=80',
    providerId: 'unicamp'
  },
  {
    title: 'Exposição de Arte Contemporânea: Luz & Movimento',
    category: 'Exposição',
    date: '01/09 - 30/09',
    time: '10:00 - 18:00',
    address: 'MACC - Museu de Arte Contemporânea - Rua Benjamin Constant, 1633 - Centro',
    city: 'Campinas - SP',
    price: 'Gratuito',
    isPaid: false,
    organizer: 'MACC & Coletivos Artísticos',
    officialLink: 'https://macc.campinas.sp.gov.br/exposicao-luz-movimento',
    image: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=800&q=80',
    providerId: 'museus'
  }
];
